### ISSUE TITLE
Can't play online anymore due to a bug after using gg-struggle for a day

### ISSUE THREAD

**Issue by VinylNix** [tsaibermelon/gg-struggle#9]
At first, everything was working well, but today, having used this app for a total of one day, the game started to show the error seen below on the screenshot. There's also an error within the console of the app, seen on the other screenshot. 

To resolve the issue I've tried:

- Launching the game with and without gg-struggle
- Reinstalling the game (in Steam)
- Verifying game files (in Steam)
- Rebooting PC
- Deleting all files associated with the Strive's profile and settings (at %LOCALAPPDATA%\GGST\Saved)
- Deleting everything associated with gg-struggle (including all the gg-struggle files which are located in the TEMP folder) and reinstalling it

The result is the same, nothing changes and I can't play the game because I always, no matter what, get this network error now.

Can anybody please help me resolve this issue? I'm not a programmer and I don't understand what happened here, I simply wanted the game to load faster, but now I can't play at all.

<img width="960" alt="Untitled2" src="https://user-images.githubusercontent.com/9739129/125429443-069dda96-91d7-48bb-86d7-f275285156ac.png">
<img width="670" alt="Untitled" src="https://user-images.githubusercontent.com/9739129/125429451-e32240f6-f3ab-484a-8e9a-b2faaed6f1df.png">

**Comment by VinylNix** [comment]
Here's the log file (and the other files) from the gg-struggle folder in TEMP:

[all.log](https://github.com/tsaibermelon/gg-struggle/files/6807788/all.log)
[gg-struggle.zip](https://github.com/tsaibermelon/gg-struggle/files/6807791/gg-struggle.zip)

**Comment by Mithrae1** [comment]
I am experiencing the exact same issue. I saw the hotfix but it misses step two going to step three instantly and telling me to run notepad as administrator. I am not sure whether I have to change the "hosts" file in system32/drivers/etc but i'll refrain from doing something drastic right now.

I hope there is a way to actually revert the changes since I had to do the manual installation because the installer was not there for quite some time.

**Comment by VinylNix** [comment]
> I am experiencing the exact same issue. I saw the hotfix but it misses step two going to step three instantly and telling me to run notepad as administrator. I am not sure whether I have to change the "hosts" file in system32/drivers/etc but i'll refrain from doing something drastic right now.
> 
> I hope there is a way to actually revert the changes since I had to do the manual installation because the installer was not there for quite some time.

Thanks for joining in! So were you able to make it work and actually go online? Is there something that can be done manually to fix this issue to be able to play online with or without gg-struggle?

**Comment by Mithrae1** [comment]
I decided to just uninstall using what the Readme.md told me at the bottom. That worked but I did not like the load times, atleast it works again haha. 

EDIT: Ah I see you haven't tried that. Since the install edits things internally on your computer you have to edit those out again. Do what the Readme.md says and it should work fine again. Deleting the files that launch the program itself won't do much unfortunately.

**Comment by VinylNix** [comment]
> I decided to just uninstall using what the Readme.md told me at the bottom. That worked but I did not like the load times, atleast it works again haha.
> 
> EDIT: Ah I see you haven't tried that. Since the install edits things internally on your computer you have to edit those out again. Do what the Readme.md says and it should work fine again. Deleting the files that launch the program itself won't do much unfortunately.

I've done that and the online mode works again now. Thanks for the help!
